repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.3
  hooks:
    # Run the linter. <- TODO: fix all the issues found by the linter
    # - id: ruff
    # Run the formatter.
    - id: ruff-format